### ISSUE TITLE
Compress all assets for quicker load

### ISSUE THREAD

**Issue by marospekarik** [DimensionLab/simlai-web#204]
<img width="578" alt="image" src="https://github.com/DimensionLab/simlai-web/assets/14806065/17edb759-e6d0-4c26-9c07-1b52feb73a78">
Currently some gifs and images are too large, resulting in a slow loading experience. We should always run images and gifs through TinyPNG or something similar.

**Comment by tohrxyz** [comment]
this will be fixed with the merge from [update-next14-app-router-huge-refactor](https://github.com/DimensionLab/simlai-web/tree/update-next14-app-router-huge-refactor) branch

**Comment by tohrxyz** [comment]
done, already in staging. will merge to prod in the next days, but closing this as essentially completed.
